name: System Test - File Uploader

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  system-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install kubectl
        shell: pwsh
        run: |
          curl.exe -Lo kubectl.exe https://dl.k8s.io/release/v1.30.0/bin/windows/amd64/kubectl.exe
          echo "$(Get-Location)" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Configure kubeconfig
        shell: pwsh
        run: |
          $env:KUBECONFIG = "$HOME\.kube\config"
          New-Item -ItemType Directory -Force -Path (Split-Path $env:KUBECONFIG)
          Set-Content -Path $env:KUBECONFIG -Value "${{ secrets.KUBECONFIG_CONTENTS }}"
          Write-Host "Kubeconfig configured"
        env:
          KUBECONFIG_CONTENTS: ${{ secrets.KUBECONFIG_CONTENTS }}

      - name: Verify cluster access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Restore
        run: dotnet restore

      - name: Build solution
        run: dotnet build

      - name: Start uploader services
        shell: pwsh
        run: |
          $startScript = "$(Get-Location)\..\bin\x64\debug\Deploy\Scripts\start.ps1"
          Write-Host "Running $startScript"
          & $startScript

      - name: Build and Test
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.FullName -match "_sTest" } | ForEach-Object {
          $projName = $_.BaseName
          dotnet test $_.FullName `
          --configuration Debug `
          --logger "trx;LogFileName=${projName}_results.trx" `
          --results-directory ./TestResults
          }

      - name: Stop uploader services
        if: always()
        shell: pwsh
        run: |
          $stopScript = "$(Get-Location)\..\bin\x64\debug\Deploy\Scripts\stop.ps1"
          Write-Host "Running $stopScript"
          & $stopScript

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./TestResults

      - name: Report Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: System Tests
          path: ./TestResults/*.trx
          reporter: dotnet-trx
